version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - andarist
  - emcc
  - funcs
  - hotscript
  - indexmap
  - instrs
  - Trunc
  - typeconstraint
  - valtype
ignoreWords: []
import: []
