version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Alloc
  - andarist
  - dblass
  - Deque
  - dipset
  - divs
  - divu
  - emcc
  - errno
  - Expecto
  - funcs
  - hotscript
  - indexmap
  - instrs
  - memcpy
  - memset
  - omnisciences
  - Omniverse
  - Patronum
  - prolly
  - remu
  - Sarlacc
  - Trunc
  - typeconstraint
  - valtype
  - wabt
ignoreWords: []
import: []
