version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Alloc
  - andarist
  - dblass
  - emcc
  - errno
  - funcs
  - hotscript
  - indexmap
  - instrs
  - memcpy
  - memset
  - Trunc
  - typeconstraint
  - valtype
ignoreWords: []
import: []
